// 报告数据 - 每天更新这部分
const reportData = {
  date: '2026-03-12',
  newFollows: [
    { name: '@dr_cintas', desc: 'AI Agent 相关', category: 'ai' },
    { name: '@trailofbits', desc: '顶级区块链安全公司', category: 'security' },
    { name: '@dguido', desc: 'Trail of Bits 创始人', category: 'security' },
    { name: '@Chain_GPT', desc: 'AI 智能合约审计', category: 'security' },
    { name: '@coinbureau', desc: '加密货币新闻/分析', category: 'crypto' },
  ],
  highlights: [
    {
      category: 'ai',
      title: 'Skill-creator 重大更新',
      desc: 'Anthropic 官方 Skills 生成器新增评估系统、基准测试、多代理并行测试功能',
      link: 'https://github.com/anthropics/skills/tree/main/skills/skill-creator',
    },
    {
      category: 'crypto',
      title: 'MultiversX Battle of Nodes',
      desc: '$150k 奖金的区块链压力测试已于 3 月 11 日开始',
      link: 'https://multiversx.com/battle-of-nodes',
    },
    {
      category: 'security',
      title: 'Trail of Bits Claude Skills',
      desc: '17 个安全技能包发布，助力 AI 辅助安全研究',
      link: 'https://github.com/trailofbits/skills',
    },
    {
      category: 'ai',
      title: 'ClickHouse 数据库基准',
      desc: '分析型工作负载比 Snowflake/Databricks 快 10 倍',
      link: 'https://clickhouse.com/blog/benchmark-2025',
    },
    {
      category: 'crypto',
      title: 'Ethereum 安全升级',
      desc: '以太坊基金会启动"万亿安全"计划第二阶段',
      link: 'https://ethereum.foundation/security',
    },
    {
      category: 'security',
      title: 'Claude Code Security',
      desc: 'OpenAI 发布 Codex Security 应用安全代理',
      link: 'https://openai.com/codex',
    },
  ],
}

const categoryLabels: Record<string, string> = {
  ai: 'AI',
  crypto: '区块链',
  security: '安全',
}

const categoryColors: Record<string, string> = {
  ai: 'category-ai',
  crypto: 'category-crypto',
  security: 'category-security',
}

export default function Home() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-8">
          <h1 className="text-4xl font-bold gradient-text mb-2">X Daily Report</h1>
          <p className="text-muted">每天早上 7:00 自动推送 · AI · 区块链 · 安全</p>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8">
        {/* Date */}
        <div className="mb-8">
          <span className="text-sm text-muted">📅 {reportData.date}</span>
        </div>

        {/* New Follows */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <span>✨</span> 新关注博主
          </h2>
          <div className="glass-card rounded-2xl p-5 grid gap-3">
            {reportData.newFollows.map((follow, i) => (
              <div key={i} className="flex items-center gap-3">
                <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${categoryColors[follow.category]}`}>
                  {categoryLabels[follow.category]}
                </span>
                <span className="font-medium text-white">{follow.name}</span>
                <span className="text-muted text-sm">· {follow.desc}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Highlights */}
        <section>
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <span>🔥</span> 精彩内容
          </h2>
          <div className="grid gap-4">
            {reportData.highlights.map((item, i) => (
              <a
                key={i}
                href={item.link}
                target="_blank"
                rel="noopener noreferrer"
                className="link-card glass-card rounded-2xl p-5 border border-border transition-all duration-300 block"
              >
                <div className="flex items-start gap-3">
                  <span className={`px-2.5 py-1 rounded-full text-xs font-medium shrink-0 ${categoryColors[item.category]}`}>
                    {categoryLabels[item.category]}
                  </span>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-white mb-1">{item.title}</h3>
                    <p className="text-muted text-sm">{item.desc}</p>
                    <span className="text-primary text-sm mt-2 inline-flex items-center gap-1">
                      查看原文 →
                    </span>
                  </div>
                </div>
              </a>
            ))}
          </div>
        </section>

        {/* Footer */}
        <footer className="mt-16 pt-8 border-t border-border text-center text-muted text-sm">
          <p>🤖 Generated by Nora · OpenClaw AI Assistant</p>
          <p className="mt-2">每天自动获取 X 优质内容并生成报告</p>
        </footer>
      </main>
    </div>
  )
}
